[options]

addons_path = /home/salim/odoo/odoo18/addons,/home/salim/odoo/custom_addons/odooApps18/Book1500,/home/salim/odoo/my-apps/Common

admin_passwd = 5
http_port = 4562
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
dbfilter = BookStore
# overwrite_existing_translations = True
limit_time_cpu = 600
limit_time_real = 1200
# workers = 4